name: "Homepage Dashboard"
description: "A highly customizable dashboard for your home server."
version: "1.0.1-a1"
slug: "homepage_dashboard"
image: ksw8954/homepage-dashboard
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 3000
panel_icon: "mdi:view-dashboard"
map:
  - addon_config:rw
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Homepage 웹 인터페이스"
options:
  port: 3000
  npm_username: ""
  npm_password: ""
  portainer_key: ""
  homeassistant_token: ""
  gitea_token: ""
  synology_username: ""
  synology_password: ""
schema:
  port: port
  npm_username: str?
  npm_password: str?
  portainer_key: str?
  homeassistant_token: str?
  gitea_token: str?
  synology_username: str?
  synology_password: str?
