name: "Homepage Dashboard"
description: "A highly customizable dashboard for your home server."
version: "1.0.3-a1"
slug: "homepage_dashboard"
image: ksw8954/homepage-dashboard
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 3000
panel_icon: "mdi:view-dashboard"
map:
  - addon_config:rw
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Homepage 웹 인터페이스"
options:
  port: 3000
  allowed_hosts: "*"
  reset_config: false
  npm_username: ""
  npm_password: ""
  portainer_key: ""
  homeassistant_token: ""
  gitea_token: ""
  synology_username: ""
  synology_password: ""
  uptime_slug: ""
  adguard_username: ""
  adguard_password: ""
  komodo_url: ""
  komodo_key: ""
  komodo_secret: ""
  qbittorrent_url: ""
  qbittorrent_username: ""
  qbittorrent_password: ""
  github_token: ""
schema:
  port: port
  allowed_hosts: str
  reset_config: bool
  npm_username: str?
  npm_password: str?
  portainer_key: str?
  homeassistant_token: str?
  gitea_token: str?
  synology_username: str?
  synology_password: str?
  uptime_slug: str?
  adguard_username: str?
  adguard_password: str?
  komodo_url: str?
  komodo_key: str?
  komodo_secret: str?
  qbittorrent_url: str?
  qbittorrent_username: str?
  qbittorrent_password: str?
  github_token: str?
