---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/onaries

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/

- 생활:
    - 2026 가계부:
        - icon: google-sheets.png
          href: https://docs.google.com/spreadsheets/d/1xZQd20Znnpx8o4w_bXVg6ZfcJXn5K5cFTS1hqy7NSOM/edit?usp=sharing
