---
# 위젯 설정: https://gethomepage.dev/configs/info-widgets/

- openmeteo:
    label: 울산
    latitude: 35.538376
    longitude: 129.311356
    timezone: Asia/Seoul
    units: metric
    cache: 5

- datetime:
    locale: ko
    format:
      timeStyle: short
      dateStyle: full
      hour12: false

- search:
    provider: google
    target: _blank

- resources:
    label: 서버
    cpu: true
    memory: true

- synology:
    label: NAS
    url: http://192.168.200.100:5000
    username: "{{HOMEPAGE_VAR_SYNOLOGY_USERNAME}}"
    password: "{{HOMEPAGE_VAR_SYNOLOGY_PASSWORD}}"
    cpu: true
    mem: true
    storage: true
    temp: true
